### DISCUSSION TITLE
strange login page

### DISCUSSION THREAD

**Discussion by iamLazyCode** [chevereto/chevereto#61] [Q&A]
why does my starting page looks like this can some one look at this docker compose and point out what mistake i made tha its not working for me i am very new to all this

```
version: "3.9"

services:
  database:
    image: mariadb:jammy
    networks:
      - chevereto
    volumes:
      - /home/user/chevereto/database:/var/lib/mysql:rw
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: MysqlPAss123
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: 2RaLhU3HaZ8vVEoi3h8z

  php:
    image: ghcr.io/chevereto/chevereto:latest #tweak with target image to run
    networks:
      - chevereto
    volumes:
      - /home/user/chevereto/pictures:/var/www/html/images:rw
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8090:80
    environment:
      CHEVERETO_DB_HOST: database
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: 2RaLhU3HaZ8vVEoi3h8z
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_HOSTNAME: https://chevereto.domainname.com #set your hostname
      CHEVERETO_HOSTNAME_PATH: /
      CHEVERETO_HTTPS: 0
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: https://chevereto.domainname.com/images/_assets/ #hostname-aware URL
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/images/_assets/
      CHEVERETO_MAX_POST_SIZE: 2G
      CHEVERETO_MAX_UPLOAD_SIZE: 2G

volumes:
  database:
  storage:

networks:
  chevereto:
```

![image](https://github.com/chevereto/chevereto/assets/13099434/53cf529e-111c-4b6c-a23a-4fc74b6eeeb1)
